<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-09-22 09:55

$extensionPath = t3lib_extMgm::extPath('march8');
return array(
	'tx_march8_lib' => $extensionPath . 'class.tx_march8_lib.php',
	'tx_march8_pagelink' => $extensionPath . 'class.tx_march8_pagelink.php',
	'tx_march8_skinselector' => $extensionPath . 'class.tx_march8_skinselector.php',
	'tx_march8_t3dimport' => $extensionPath . 'class.tx_march8_t3dimport.php',
	'tx_march8_espacios' => $extensionPath . 'class.tx_march8_espacios.php',
	'tx_march8_media' => $extensionPath . 'class.tx_march8_media.php',
	'ux_tslib_content_media' => $extensionPath . 'class.ux_tslib_content_media.php',

);
?>